In [20]:
import numpy as np

In [28]:
print(np.pi)
print(np.cos(np.pi))
print(np.sqrt(16))
print(np.exp(5))
print(np.log(np.exp(5)))

3.141592653589793
-1.0
4.0
148.4131591025766
5.0


In [41]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(vector,'\n')
print(matrix,'\n')
print(matrix.T)

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
vector = np.arange(1,9)
print(vector)
vector1 = np.arange(1,9,2)
print(vector1)
print(vector1.T)

[1 2 3 4 5 6 7 8]
[1 3 5 7]
[1 3 5 7]


In [43]:
vector1

array([1, 3, 5, 7])

In [47]:
ar1 = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])
ar1

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])