# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.281706   0.45834072 0.02521419 0.56259927 0.35425984]
 [0.96918687 0.30869556 0.59778913 0.96174751 0.9271167 ]
 [0.03819326 0.1173124  0.77347853 0.37859068 0.62280745]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]

[[-0.02720195  0.99300003  0.28864096  0.35315241 -0.61077355]
 [ 0.49834567  0.42065216 -0.46233081 -0.96748978 -0.01534517]
 [-1.33195826  1.15729194 -0.87556513 -0.1306146   0.77826956]
 [-1.18974435  0.63657479 -0.65544978  1.04915257  0.65819181]
 [ 0.62480833 -0.47203515 -0.6304643  -0.45947162  0.90664652]
 [ 0.4860555  -1.83013288 -0.79430058 -0.30928916 -0.53115176]
 [ 1.13020132 -1.91274791  0.63269739  0.30084042 -1.70312372]
 [ 2.14696354 -1.83093667 -1.74271032 -0.42068124  1.38088794]
 [-0.87622895 -0.05983899 -0.22870501  1.23045202 -0.78418086]
 [-0.03931695 -0.51750265 -1.2254538  -1.20327951 -0.77278359]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4464512196175505
0.9449813575184138


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.025214192838928895
2.1469635368006146


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.41421763 -0.13733542  0.54536378  2.02130966  1.49075622 -0.5006987
  0.71462849  2.04145011 -0.81952411 -1.06104982 -0.2206812  -0.43182125
 -0.61882649 -0.61896896 -0.77678111  0.13614972  0.96811227  0.5594143
 -2.76803583]
0.7146284863663109


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.49075622 -0.5006987   0.71462849  2.04145011 -0.81952411]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.41421763  2.02130966  0.71462849 -1.06104982 -0.61882649]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.281706   0.45834072 0.02521419 0.56259927 0.35425984]
 [0.96918687 0.30869556 0.59778913 0.96174751 0.9271167 ]
 [0.03819326 0.1173124  0.77347853 0.37859068 0.62280745]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]
0.5977891286163405
0.5977891286163405


In [19]:
print(rand_mat[0:2,1:3])

[[0.45834072 0.02521419]
 [0.30869556 0.59778913]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.41421763 -0.13733542  0.54536378  2.02130966  1.49075622 -0.5006987
  0.71462849  2.04145011 -0.81952411 -1.06104982 -0.2206812  -0.43182125
 -0.61882649 -0.61896896 -0.77678111  0.13614972  0.96811227  0.5594143
 -2.76803583]

[ 1.41421763 -0.13733542  0.54536378  4.          4.         -0.5006987
  0.71462849  2.04145011 -0.81952411 -1.06104982 -0.2206812  -0.43182125
 -0.61882649 -0.61896896 -0.77678111  0.13614972  0.96811227  0.5594143
 -2.76803583]

[ 1.41421763 -0.13733542  0.54536378  1.          2.         -0.5006987
  0.71462849  2.04145011 -0.81952411 -1.06104982 -0.2206812  -0.43182125
 -0.61882649 -0.61896896 -0.77678111  0.13614972  0.96811227  0.5594143
 -2.76803583]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.281706   0.45834072 0.02521419 0.56259927 0.35425984]
 [0.96918687 0.30869556 0.59778913 0.96174751 0.9271167 ]
 [0.03819326 0.1173124  0.77347853 0.37859068 0.62280745]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]

[[0.281706   0.45834072 0.02521419 0.56259927 0.35425984]
 [0.96918687 0.30869556 0.59778913 0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.281706   0.45834072 0.02521419]
 [0.96918687 0.30869556 0.59778913]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.         3.         0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.         3.         0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.69491078  0.0020463   0.75518499 -0.96654395  0.79005306  1.17992745
  1.1429544   0.00975449 -0.36999385 -0.12623842 -0.10907778 -0.21077692
  0.48864226 -1.32776772  0.06641059]
[False  True  True False  True  True  True  True False False False False
  True False  True]
[0.0020463  0.75518499 0.79005306 1.17992745 1.1429544  0.00975449
 0.48864226 0.06641059]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.02720195  0.99300003  0.28864096  0.35315241 -0.61077355]
 [ 0.49834567  0.42065216 -0.46233081 -0.96748978 -0.01534517]
 [-1.33195826  1.15729194 -0.87556513 -0.1306146   0.77826956]
 [-1.18974435  0.63657479 -0.65544978  1.04915257  0.65819181]
 [ 0.62480833 -0.47203515 -0.6304643  -0.45947162  0.90664652]
 [ 0.4860555  -1.83013288 -0.79430058 -0.30928916 -0.53115176]
 [ 1.13020132 -1.91274791  0.63269739  0.30084042 -1.70312372]
 [ 2.14696354 -1.83093667 -1.74271032 -0.42068124  1.38088794]
 [-0.87622895 -0.05983899 -0.22870501  1.23045202 -0.78418086]
 [-0.03931695 -0.51750265 -1.2254538  -1.20327951 -0.77278359]]
[0.99300003 0.28864096 0.35315241 0.49834567 0.42065216 1.15729194
 0.77826956 0.63657479 1.04915257 0.65819181 0.62480833 0.90664652
 0.4860555  1.13020132 0.63269739 0.30084042 2.14696354 1.38088794
 1.23045202]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.69491078  0.0020463   0.75518499 -0.96654395  0.79005306  1.17992745
  1.1429544   0.00975449 -0.36999385 -0.12623842 -0.10907778 -0.21077692
  0.48864226 -1.32776772  0.06641059]

[-6.94910779e-01  2.04629869e-03 -5.00000000e+00 -9.66543947e-01
 -5.00000000e+00 -5.00000000e+00 -5.00000000e+00  9.75449361e-03
 -3.69993845e-01 -1.26238418e-01 -1.09077778e-01 -2.10776916e-01
  4.88642257e-01 -1.32776772e+00  6.64105883e-02]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.02720195  0.99300003  0.28864096  0.35315241 -0.61077355]
 [ 0.49834567  0.42065216 -0.46233081 -0.96748978 -0.01534517]
 [-1.33195826  1.15729194 -0.87556513 -0.1306146   0.77826956]
 [-1.18974435  0.63657479 -0.65544978  1.04915257  0.65819181]
 [ 0.62480833 -0.47203515 -0.6304643  -0.45947162  0.90664652]
 [ 0.4860555  -1.83013288 -0.79430058 -0.30928916 -0.53115176]
 [ 1.13020132 -1.91274791  0.63269739  0.30084042 -1.70312372]
 [ 2.14696354 -1.83093667 -1.74271032 -0.42068124  1.38088794]
 [-0.87622895 -0.05983899 -0.22870501  1.23045202 -0.78418086]
 [-0.03931695 -0.51750265 -1.2254538  -1.20327951 -0.77278359]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.         3.         0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]

[[-0.02720195  0.99300003  0.28864096  0.35315241 -0.61077355]
 [ 0.49834567  0.42065216 -0.46233081 -0.96748978 -0.01534517]
 [-1.33195826  1.15729194 -0.87556513 -0.1306146   0.77826956]
 [-1.18974435  0.63657479 -0.65544978  1.04915257  0.65819181]
 [ 0.62480833 -0.47203515 -0.6304643  -0.45947162  0.90664652]
 [ 0.4860555  -1.83013288 -0.79430058 -0.30928916 -0.53115176]
 [ 1.13020132 -1.91274791  0.63269739  0.30084042 -1.70312372]
 [ 2.14696354 -1.83093667 -1.74271032 -0.42068124  1.38088794]
 [-0.87622895 -0.05983899 -0.22870501  1.23045202 -0.78418086]
 [-0.03931695 -0.51750265 -1.2254538  -1.20327951 -0.77278359]]
[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.         3.         0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]

[[3.         3.         3.         0.56259927 0.35425984]
 [3.         3.         3.         0.         0.        ]
 [0.03819326 0.1173124  0.77347853 0.         0.        ]
 [0.05651548 0.04633485 0.06289464 0.63460988 0.61574926]
 [0.99224152 0.28769496 0.32503291 0.57569366 0.18747521]]
